name = "byh16worker"
main = "src/index.js"
compatibility_date = "2025-01-01"

[vars]
NODE_ENV = "development"
APP_NAME = "cf-api"
MONGO_APP_ID = "opmiyeka"
MONGO_API_KEY = "c1ead0d8-b623-4068-9d41-84333a81f570"
MONGO_CLUSTER = "0"
MONGO_DB = "byh16"
