name = "byh16worker"
main = "src/index.js"
compatibility_date = "2025-01-01"

[vars]
NODE_ENV = "development"
APP_NAME = "cf-api"

[[d1_databases]]
binding = "DB"
database_name = "byh16"
database_id = "c4418813-ba2e-48ab-a6f5-1b27375d2ebd"
